export const QUERY_KEYS = {
  ASSETS_QUERY: 'ASSETS_QUERY',
  COLLECTIONS_QUERY: 'COLLECTIONS_QUERY',
  MY_COLLECTIONS_QUERY: 'MY_COLLECTIONS_QUERY',
  MY_ASSETS_QUERY: 'MY_ASSETS_QUERY',
  NFTS: 'NFTS',
  NFT: 'NFT',
  BANNER: 'BANNER',
  CATEGORIES: 'CATEGORIES',
  COLLECTIONS: 'COLLECTIONS',
  ADDRESS: 'ADDRESS',
  WHITELIST: 'WHITELIST',
  ACCOUNTS: 'ACCOUNTS',
  NFTSCollect: 'NFTSCollect',
  hotNFTS: 'hotNFTS',
  USER: 'USER',
  USERTop: 'USERTop',
  Offer: 'Offer',
  OfferSend: 'OfferSend',
  Event: 'Event',
  ExpensiveNFTS: 'ExpensiveNFTS',
  CheapNFTS: 'CheapNFTS',
  CATEGORIEINFO: 'CATEGORIEINFO',
  Historyprice: 'Historyprice',
  Artist: 'Artist',
  Transaction: 'Transaction',
};

export const DEFAULT_PAGE_LIMIT = 20;
